name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows exe
        run: flutter build windows

      - name: Zip build folder
        run: |
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath windows_build.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: windows_build.zip
